/**
 * main.c -- LD-ToyPad Bridge .sprx Plugin (Sony SDK / -mprx)
 *
 * Sony SDK -mprx, NO inline assembly PRX metadata.
 * SYS_MODULE_INFO / SYS_MODULE_START / SYS_MODULE_STOP
 * from <sys/prx.h> generate .rodata.sceModuleInfo + .lib.ent.
 * .lib.stub is auto-generated by -mprx from stub libraries.
 * NO PSL1GHT, NO inline asm collisions.
 *
 * PAPERTRAIL LOGGING:
 *   Every step logs to /dev_hdd0/plugins/ldtoypad_boot.log via
 *   cellFsWrite(). module_start returns 0 (SYS_PRX_RESIDENT)
 *   on success or 1 (SYS_PRX_NO_RESIDENT) on failure.
 *
 * THREADING:
 *   module_start creates a joinable background thread (prio 1000,
 *   64KB stack). module_stop signals shutdown & joins.
 */

#include <sys/prx.h>
#include <sys/ppu_thread.h>
#include <cell/cell_fs.h>
#include <cell/sysmodule.h>
#include <string.h>
#include <stddef.h>

SYS_MODULE_INFO(ldtoypad, 0, 1, 1);
SYS_MODULE_START(module_start);
SYS_MODULE_STOP(module_stop);

static int papertrail(const char *msg);
static void worker_thread(uint64_t arg);

static volatile int g_shutdown = 0;
static sys_ppu_thread_t g_worker_tid = SYS_PPU_THREAD_ID_INVALID;

/* Write a line to the boot log */
static int papertrail(const char *msg)
{
    int fd;
    uint64_t written;
    const char *prefix = "[LDTP] ";

    if (cellFsOpen("/dev_hdd0/plugins/ldtoypad_boot.log",
                   CELL_FS_O_WRONLY | CELL_FS_O_CREAT | CELL_FS_O_APPEND,
                   &fd, NULL, 0) != CELL_OK)
        return -1;
    cellFsWrite(fd, prefix, strlen(prefix), &written);
    cellFsWrite(fd, msg, strlen(msg), &written);
    cellFsWrite(fd, "\n", 1, &written);
    cellFsClose(fd);
    return 0;
}

/* Raw syscall 74: usleep */
static inline int sys_usleep(uint64_t usec)
{
    register uint64_t num __asm__("r3") = 74;
    register uint64_t arg1 __asm__("r4") = usec;
    __asm__ volatile("sc\n" : "+r"(num) : "r"(arg1)
                     : "memory", "cr0", "r11", "r12");
    return (int)num;
}

/* module_start - called by Cobra PRX loader */
int module_start(size_t args, void *argp)
{
    (void)args; (void)argp;
    int ret;

    papertrail("=== ldtoypad module_start ===");

    /* Load sysmodule dependencies */
    papertrail("Step 1: Loading CELL_SYSMODULE_FS...");
    ret = cellSysmoduleLoadModule(CELL_SYSMODULE_FS);
    if (ret != CELL_OK) { papertrail("FAIL: FS"); return 1; }
    papertrail("OK: FS loaded");

    papertrail("Step 2: Loading CELL_SYSMODULE_NET...");
    ret = cellSysmoduleLoadModule(CELL_SYSMODULE_NET);
    if (ret != CELL_OK) { papertrail("FAIL: NET"); return 1; }
    papertrail("OK: NET loaded");

    papertrail("Step 3: Loading CELL_SYSMODULE_USBD...");
    ret = cellSysmoduleLoadModule(CELL_SYSMODULE_USBD);
    if (ret != CELL_OK) { papertrail("FAIL: USBD"); return 1; }
    papertrail("OK: USBD loaded");

    /* Create worker thread */
    papertrail("Step 4: Creating worker thread...");
    ret = sys_ppu_thread_create(&g_worker_tid,
                                (void(*)(uint64_t))worker_thread,
                                0, 1000, 64*1024,
                                SYS_PPU_THREAD_CREATE_JOINABLE,
                                "ldtoypad_worker");
    if (ret != CELL_OK) { papertrail("FAIL: thread create"); return 1; }
    papertrail("OK: thread created");

    papertrail("=== module_start SUCCESS ===");
    return 0; /* SYS_PRX_RESIDENT */
}

/* module_stop - called by Cobra PRX loader */
int module_stop(size_t args, void *argp)
{
    (void)args; (void)argp;
    papertrail("=== module_stop ===");
    g_shutdown = 1;
    if (g_worker_tid != SYS_PPU_THREAD_ID_INVALID) {
        uint64_t ev = 0;
        sys_ppu_thread_join(g_worker_tid, &ev);
        g_worker_tid = SYS_PPU_THREAD_ID_INVALID;
        papertrail("OK: worker joined");
    }
    papertrail("=== module_stop SUCCESS ===");
    return SYS_PRX_STOP_OK;
}

/* Forward declarations for subsystem modules */
extern void debug_init(void);
extern void debug_shutdown(void);
extern void toypad_state_init(void);
extern void toypad_state_deinit(void);
extern int  network_init(uint16_t port);
extern void network_shutdown(void);
extern int  network_recv(uint8_t *buf, int size);
extern int  ldd_driver_init(void);
extern void ldd_driver_shutdown(void);

/* Worker thread body */
static void worker_thread(uint64_t arg)
{
    (void)arg;
    papertrail("=== worker_thread started ===");

    papertrail("Step 5: debug_init()...");
    debug_init();
    papertrail("OK: debug_init");

    papertrail("Step 6: toypad_state_init()...");
    toypad_state_init();
    papertrail("OK: toypad_state_init");

    papertrail("Step 7: network_init(28472)...");
    if (network_init(28472) != 0)
        papertrail("WARN: network_init failed, continuing");
    else
        papertrail("OK: network_init");

    papertrail("Step 8: ldd_driver_init()...");
    if (ldd_driver_init() != 0)
        papertrail("NOTE: ldd_driver_init not supported, network-only mode");
    else
        papertrail("OK: ldd_driver_init");

    papertrail("=== All subsystems initialized ===");

    /* Main loop */
    while (!g_shutdown) {
        uint8_t buf[80];
        if (network_recv(buf, sizeof(buf)) > 0)
            papertrail("RX: network packet");
        sys_usleep(10000);
    }

    papertrail("=== Shutting down ===");
    ldd_driver_shutdown();
    network_shutdown();
    toypad_state_deinit();
    debug_shutdown();
    papertrail("=== worker_thread EXIT ===");
    sys_ppu_thread_exit(0);
}
