/**
 * main.c -- LD-ToyPad Bridge .sprx Plugin (Sony SDK / -mprx)
 *
 * Sony SDK -mprx, NO inline assembly PRX metadata.
 * SYS_MODULE_INFO / SYS_MODULE_START / SYS_MODULE_STOP
 * from <sys/prx.h> generate .rodata.sceModuleInfo + .lib.ent.
 * .lib.stub is auto-generated by -mprx from stub libraries.
 * NO PSL1GHT, NO inline asm collisions.
 *
 * PAPERTRAIL LOGGING:
 *   Every step logs to /dev/hdd0/plugins/ldtoypad_boot.log via
 *   cellFsWrite(). module_start returns 0 (SYS_PRX_RESIDENT)
 *   on success or 1 (SYS_PRX_NO_RESIDENT) on failure.
 *
 * THREADING:
 *   module_start creates a joinable background thread (prio 1000,
 *   64KB stack). module_stop signals shutdown & joins.
 *   ALL heavy lifting (sysmodules, USB, network) happens in
 *   worker_thread to avoid blocking Cobra's loader.
 */

#include <sys/prx.h>
#include <sys/ppu_thread.h>
#include <cell/cell_fs.h>
#include <cell/sysmodule.h>
#include <string.h>
#include <stddef.h>

#include "syscall.h"

SYS_MODULE_INFO(ldtoypad, 0, 1, 1);
SYS_MODULE_START(module_start);
SYS_MODULE_STOP(module_stop);

static int papertrail(const char *msg);
static void worker_thread(uint64_t arg);

static volatile int g_shutdown = 0;
static sys_ppu_thread_t g_worker_tid = SYS_PPU_THREAD_ID_INVALID;

/* CELL_SYSMODULE_ERROR_DUPLICATED might not be defined in all SDKs */
#ifndef CELL_SYSMODULE_ERROR_DUPLICATED
#define CELL_SYSMODULE_ERROR_DUPLICATED 0x8002a002
#endif

/* Write a line to the boot log */
static int papertrail(const char *msg)
{
    int fd;
    uint64_t written;
    const char *prefix = "[LDTP] ";

    if (cellFsOpen("/dev_hdd0/plugins/ldtoypad_boot.log",
                   CELL_FS_O_WRONLY | CELL_FS_O_CREAT | CELL_FS_O_APPEND,
                   &fd, NULL, 0) != CELL_OK)
        return -1;
    cellFsWrite(fd, prefix, strlen(prefix), &written);
    cellFsWrite(fd, msg, strlen(msg), &written);
    cellFsWrite(fd, "\n", 1, &written);
    cellFsClose(fd);
    return 0;
}

/**
 * module_start - called by Cobra PRX loader
 *
 * MUST return quickly. Delegate all initialization to worker_thread.
 * Do NOT call cellSysmoduleLoadModule here - do it in the thread.
 */
int module_start(size_t args, void *argp)
{
    (void)args; (void)argp;
    int ret;

    papertrail("=== ldtoypad module_start ===");

    /* Create worker thread - it will load sysmodules and init subsystems */
    papertrail("Step 1: Creating worker thread...");
    ret = sys_ppu_thread_create(&g_worker_tid,
                                (void(*)(uint64_t))worker_thread,
                                0, 1000, 64*1024,
                                SYS_PPU_THREAD_CREATE_JOINABLE,
                                "ldtoypad_worker");
    if (ret != CELL_OK) { papertrail("FAIL: thread create"); return 1; }
    papertrail("OK: thread created");

    papertrail("=== module_start returning 0 (RESIDENT) ===");
    return 0; /* SYS_PRX_RESIDENT */
}

/**
 * module_stop - called by Cobra PRX loader on unload
 *
 * Note: Cobra 8.5 expects int module_stop(void), NOT
 * module_stop(size_t, void*).  The void signature matches
 * the working hello-plugin.
 */
int module_stop(void)
{
    papertrail("=== module_stop ===");
    g_shutdown = 1;
    if (g_worker_tid != SYS_PPU_THREAD_ID_INVALID) {
        uint64_t ev = 0;
        sys_ppu_thread_join(g_worker_tid, &ev);
        g_worker_tid = SYS_PPU_THREAD_ID_INVALID;
        papertrail("OK: worker joined");
    }
    papertrail("=== module_stop SUCCESS ===");
    return SYS_PRX_STOP_OK;
}

/* Forward declarations for subsystem modules */
extern void debug_init(void);
extern void debug_shutdown(void);
extern void toypad_state_init(void);
extern void toypad_state_deinit(void);
extern int  network_init(uint16_t port);
extern void network_wait_ready(void);
extern void network_shutdown(void);
extern int  network_recv(uint8_t *buf, int size);
extern int  ldd_driver_init(void);
extern void ldd_driver_shutdown(void);

/* Helper: load sysmodule, tolerate DUPLICATED */
static int load_sysmodule(uint16_t id, const char *name)
{
    int ret = cellSysmoduleLoadModule(id);
    if (ret == CELL_OK) {
        papertrail(name); papertrail("OK: loaded");
        return 0;
    }
    if (ret == CELL_SYSMODULE_ERROR_DUPLICATED) {
        papertrail(name); papertrail("OK: already loaded (dupe)");
        return 0;
    }
    papertrail(name); papertrail("FAIL");
    return -1;
}

/* Worker thread body - runs all initialization */
static void worker_thread(uint64_t arg)
{
    (void)arg;
    papertrail("=== worker_thread started ===");

    /* Step 1: Load sysmodules (in thread, not loader) */
    papertrail("Step 2: Loading sysmodules...");
    if (load_sysmodule(CELL_SYSMODULE_FS,   "FS")   != 0) goto fail;
    if (load_sysmodule(CELL_SYSMODULE_NET,  "NET")  != 0) goto fail;
    if (load_sysmodule(CELL_SYSMODULE_USBD, "USBD") != 0) goto fail;

    papertrail("Step 3: debug_init()...");
    debug_init();
    papertrail("OK: debug_init");

    papertrail("Step 4: toypad_state_init()...");
    toypad_state_init();
    papertrail("OK: toypad_state_init");

    papertrail("Step 5: network_init(28472)...");
    if (network_init(28472) != 0) {
        papertrail("WARN: network_init failed, continuing");
    } else {
        papertrail("OK: network_init");
        papertrail("Step 5b: network_wait_ready()...");
        network_wait_ready();
        papertrail("OK: network_wait_ready");
    }

    papertrail("Step 6: ldd_driver_init()...");
    if (ldd_driver_init() != 0)
        papertrail("NOTE: ldd_driver_init not supported, network-only mode");
    else
        papertrail("OK: ldd_driver_init");

    papertrail("=== All subsystems initialized ===");

    /* Main loop */
    while (!g_shutdown) {
        uint8_t buf[80];
        if (network_recv(buf, sizeof(buf)) > 0)
            papertrail("RX: network packet");
        sys_usleep(10000);
    }

    papertrail("=== Shutting down ===");
    ldd_driver_shutdown();
    network_shutdown();
    toypad_state_deinit();
    debug_shutdown();
    papertrail("=== worker_thread EXIT ===");
    sys_ppu_thread_exit(0);
    return;

fail:
    papertrail("=== worker_thread FAILED - exiting ===");
    sys_ppu_thread_exit(1);
}
