/**
 * usb_hooks.c — Fake cellUsbd Wrappers for Toy Pad Emulation
 *
 * Implements replacement functions for the LEGO Dimensions game's
 * cellUsbd imports. Toy Pad traffic is routed to the Node.js server
 * via UDP. Non-Toy-Pad traffic passes through to real LV2 via trampoline.
 *
 * Architecture:
 *   my_cellUsbdInit()        → return CELL_OK (skip real USB init)
 *   my_cellUsbdOpenPipe()    → allocate virtual pipe handle
 *   my_cellUsbdTransfer()    → IN: poll server / OUT: forward to server
 *   my_cellUsbdClosePipe()   → free virtual pipe handle
 *
 * TOC management:
 *   The game calls us with its TOC in r2. We need to switch to our
 *   PRX's TOC before accessing our global variables (.data/.bss).
 *   This is handled by the function prologue generated by the Sony SDK
 *   compiler when -mprx is used (it references __toc automatically).
 *
 *   IMPORTANT: Since our hook functions ARE the replacement (called
 *   directly by the game via ba), the regular PRX function prologue
 *   does NOT save the game's r2. Our preamble in hook.c must handle
 *   this. For now, we rely on the fact that PowerPC calling convention
 *   requires r2 to be preserved across calls — the game's compiler
 *   will save/restore r2 around its call to cellUsbdXxx.
 */

#include <string.h>
#include <stdint.h>
#include <stddef.h>

#include "hook.h"
#include "usb_hooks.h"
#include "network.h"
#include "debug.h"

/* ---------------------------------------------------------------
 * Global state
 * --------------------------------------------------------------- */
usb_hook_state_t g_usb_hooks;

/* ---------------------------------------------------------------
 * Token USB error/status codes
 * --------------------------------------------------------------- */
#define CELL_OK                    0
#define CELL_USBD_ERROR_FAILED    -1

/* ---------------------------------------------------------------
 * Toy Pad Pipe Tracking
 * --------------------------------------------------------------- */

int usb_hook_is_toypad_pipe(uint32_t pipe_handle)
{
    int i;
    for (i = 0; i < USB_HOOK_MAX_PIPES; i++) {
        if (g_usb_hooks.pipes[i].in_use &&
            g_usb_hooks.pipes[i].pipe_handle == pipe_handle) {
            /* Return 1 for IN, 2 for OUT */
            if (g_usb_hooks.pipes[i].ep_addr == TOYPAD_EP_IN)
                return 1;
            if (g_usb_hooks.pipes[i].ep_addr == TOYPAD_EP_OUT)
                return 2;
            return 0;
        }
    }
    return 0;
}

usb_hook_pipe_t *usb_hook_lookup_pipe(uint32_t pipe_handle)
{
    int i;
    for (i = 0; i < USB_HOOK_MAX_PIPES; i++) {
        if (g_usb_hooks.pipes[i].in_use &&
            g_usb_hooks.pipes[i].pipe_handle == pipe_handle) {
            return &g_usb_hooks.pipes[i];
        }
    }
    return NULL;
}

/* ---------------------------------------------------------------
 * Internal: Allocate a virtual pipe slot
 * --------------------------------------------------------------- */
static usb_hook_pipe_t *alloc_pipe(void)
{
    int i;
    uint32_t handle;

    handle = ++g_usb_hooks.next_pipe_id;
    if (handle == 0) handle = ++g_usb_hooks.next_pipe_id; /* skip 0 */

    for (i = 0; i < USB_HOOK_MAX_PIPES; i++) {
        if (!g_usb_hooks.pipes[i].in_use) {
            g_usb_hooks.pipes[i].in_use = 1;
            g_usb_hooks.pipes[i].pipe_handle = handle;
            g_usb_hooks.pipes[i].dev_id = 0;
            g_usb_hooks.pipes[i].ep_addr = 0;
            return &g_usb_hooks.pipes[i];
        }
    }

    DEBUG_ERROR("[USB] No free pipe slots!\n");
    return NULL;
}

/* ---------------------------------------------------------------
 * Internal: Free a virtual pipe slot
 * --------------------------------------------------------------- */
static void free_pipe(uint32_t pipe_handle)
{
    usb_hook_pipe_t *pipe = usb_hook_lookup_pipe(pipe_handle);
    if (pipe) {
        DEBUG_PRINT("[USB] Freed pipe handle 0x%08X (ep=0x%02X)\n",
                    (unsigned)pipe_handle, (unsigned)pipe->ep_addr);
        memset(pipe, 0, sizeof(*pipe));
    }
}

/* ---------------------------------------------------------------
 * Internal: Extract endpoint address from a standard USB endpoint
 * descriptor. The descriptor is 7 bytes:
 *   byte 0: bLength (0x07)
 *   byte 1: bDescriptorType (0x05 = ENDPOINT)
 *   byte 2: bEndpointAddress  (bit 7 = direction, bits 3-0 = number)
 *   byte 3: bmAttributes
 *   byte 4-5: wMaxPacketSize
 *   byte 6: bInterval
 * --------------------------------------------------------------- */
static uint8_t extract_ep_addr(const void *ep_descriptor)
{
    if (ep_descriptor == NULL) {
        return 0;
    }
    /* Endpoint address is at byte offset 2 in the descriptor. */
    return ((const uint8_t *)ep_descriptor)[2];
}

/* ---------------------------------------------------------------
 * Hook: my_cellUsbdInit
 *
 * The game calls this to initialize the USB subsystem.
 * We return CELL_OK immediately to skip real USB init.
 * The real init would enumerate USB devices — we don't need that
 * since our Toy Pad is virtual.
 * --------------------------------------------------------------- */
int my_cellUsbdInit(void)
{
    DEBUG_PRINT("[USB] cellUsbdInit() intercepted — returning CELL_OK\n");
    return CELL_OK;
}

/* ---------------------------------------------------------------
 * Hook: my_cellUsbdOpenPipe
 *
 * The game calls this to open a USB endpoint for communication.
 * We allocate a virtual pipe and return success.
 *
 * If the endpoint address matches our Toy Pad (0x81 IN or 0x01 OUT),
 * we mark it as a Toy Pad pipe. Otherwise, we route through to the
 * real LV2 USB driver via the trampoline.
 *
 * Original signature:
 *   int cellUsbdOpenPipe(uint32_t *pipe_handle, uint32_t dev_id,
 *                        void *ep_descriptor);
 *
 * We need to handle this via inline assembly since the function is
 * called directly by the game (not through our PRX import table).
 * The Sony SDK -mprx prologue handles TOC switching automatically.
 * --------------------------------------------------------------- */
int my_cellUsbdOpenPipe(uint32_t *pipe_handle, uint32_t dev_id,
                         void *ep_descriptor)
{
    uint8_t ep_addr;
    usb_hook_pipe_t *pipe;

    if (pipe_handle == NULL) {
        DEBUG_ERROR("[USB] cellUsbdOpenPipe: NULL pipe_handle\n");
        return CELL_USBD_ERROR_FAILED;
    }

    ep_addr = extract_ep_addr(ep_descriptor);

    DEBUG_PRINT("[USB] cellUsbdOpenPipe intercepted: dev_id=%u, ep=0x%02X\n",
                (unsigned)dev_id, (unsigned)ep_addr);

    /* For Toy Pad endpoints, allocate a virtual pipe. */
    if (ep_addr == TOYPAD_EP_IN || ep_addr == TOYPAD_EP_OUT) {
        pipe = alloc_pipe();
        if (pipe == NULL) {
            DEBUG_ERROR("[USB] Failed to allocate pipe for Toy Pad ep=0x%02X\n",
                        (unsigned)ep_addr);
            return CELL_USBD_ERROR_FAILED;
        }

        pipe->dev_id = dev_id;
        pipe->ep_addr = ep_addr;
        *pipe_handle = pipe->pipe_handle;

        g_usb_hooks.toypad_claimed = 1;

        DEBUG_PRINT("[USB] Toy Pad pipe opened: handle=0x%08X, ep=0x%02X\n",
                    (unsigned)pipe->pipe_handle, (unsigned)ep_addr);
        return CELL_OK;
    }

    /*
     * For non-Toy-Pad pipes, we need to call the REAL cellUsbdOpenPipe
     * via the trampoline. Since we're inside the game process, the
     * original LV2 syscall is what we saved in the trampoline.
     *
     * We use inline assembly to:
     *   1. Save our PRX's TOC (r2)
     *   2. Load the game's TOC (which was in r2 when we were called)
     *   3. Call through the trampoline
     *   4. Restore our PRX's TOC
     *   5. Return
     *
     * Arguments are already in r3, r4, r5 from our function entry.
     */
    DEBUG_VERBOSE("[USB] Non-Toy-Pad pipe open: passing through\n");

    {
        /* Forward to real LV2 via trampoline.
         * The trampoline contains the original 4 instructions followed
         * by a ba back to the original function + 16.
         * We call it like a normal function — it will execute the
         * original instructions and return to us.
         */
        typedef int (*tramp_fn_t)(uint32_t*, uint32_t, void*);
        tramp_fn_t real_open = (tramp_fn_t)(void*)&g_usb_hooks.tramp_open_pipe;
        return real_open(pipe_handle, dev_id, ep_descriptor);
    }
}

/* ---------------------------------------------------------------
 * Hook: my_cellUsbdTransfer
 *
 * THE KEY HOOK. The game calls this to perform USB transfers.
 *
 * For Toy Pad IN endpoint (0x81):
 *   - Sends poll request to PC server via network_send_poll()
 *   - Waits for response via network_recv() (non-blocking)
 *   - Populates the game's buffer with spoofed tag data
 *
 * For Toy Pad OUT endpoint (0x01):
 *   - Forwards data to PC server via network_send_data()
 *
 * For non-Toy-Pad pipes:
 *   - Calls through trampoline to real LV2 USB driver
 *
 * Original signature:
 *   int cellUsbdTransfer(uint32_t pipe_handle, void *buf, uint32_t *len,
 *                        uint32_t arg4, uint32_t arg5);
 *
 * Note: The exact argument layout varies by SDK version. The common
 * pattern is: (pipe, buf, len, arg4, arg5) where:
 *   - pipe: pipe handle
 *   - buf: data buffer
 *   - len: pointer to length (IN: max, OUT: actual)
 *   - arg4: typically transfer type or flags
 *   - arg5: typically timeout in ms
 * --------------------------------------------------------------- */
int my_cellUsbdTransfer(uint32_t pipe_handle, void *buf,
                         uint32_t *len, uint32_t arg4, uint32_t arg5)
{
    int toypad_type;

    (void)arg4;
    (void)arg5;

    /* Check if this is a Toy Pad pipe. */
    toypad_type = usb_hook_is_toypad_pipe(pipe_handle);

    if (toypad_type == 0) {
        /* Non-Toy-Pad pipe: pass through to real LV2 via trampoline. */
        typedef int (*tramp_fn_t)(uint32_t, void*, uint32_t*, uint32_t, uint32_t);
        tramp_fn_t real_xfer = (tramp_fn_t)(void*)&g_usb_hooks.tramp_transfer;
        return real_xfer(pipe_handle, buf, len, arg4, arg5);
    }

    if (toypad_type == 1) {
        /* Toy Pad IN endpoint (0x81): Poll server for tag data. */
        uint32_t max_len;
        uint8_t response[NET_PACKET_MAX_SIZE];
        uint8_t zone = 1;  /* Default zone: CENTER */
        uint8_t seq;
        int recv_len;

        if (buf == NULL || len == NULL) {
            DEBUG_ERROR("[USB] IN transfer with NULL buffer/len\n");
            return CELL_USBD_ERROR_FAILED;
        }

        max_len = *len;
        seq = (uint8_t)(g_usb_hooks.next_pipe_id++); /* cheap seq */

        /* Send poll request to PC server. */
        if (network_send_poll(zone, seq) < 0) {
            /* No server known yet — return empty response.
             * The game expects timeouts/hiccups during device init. */
            if (max_len > 0) {
                memset(buf, 0, max_len);
            }
            *len = 0;
            return CELL_OK;
        }

        /* Try to receive response (non-blocking with MSG_DONTWAIT). */
        recv_len = network_recv(response, sizeof(response));

        if (recv_len > 2 && response[0] == 0x00 /* RESPONSE_OK */) {
            /* Valid response from server — copy tag data. */
            int payload_len = recv_len - 3;
            if (payload_len > (int)max_len) {
                payload_len = (int)max_len;
            }
            if (payload_len > 0) {
                memcpy(buf, response + 3, (size_t)payload_len);
            }
            *len = (uint32_t)payload_len;
            DEBUG_VERBOSE("[USB] IN transfer: got %d bytes from server\n",
                         payload_len);
        } else if (recv_len > 2 && response[0] == 0x01 /* RESPONSE_NO_TAG */) {
            /* No tag on zone — return empty with report ID. */
            if (max_len > 0) {
                memset(buf, 0, max_len);
                ((uint8_t*)buf)[0] = 0x01;  /* HID report ID */
            }
            *len = max_len;
        } else {
            /* No response or error — return empty poll result. */
            if (max_len > 0) {
                memset(buf, 0, max_len);
                ((uint8_t*)buf)[0] = 0x01;  /* HID report ID = pad status */
            }
            *len = max_len;
            DEBUG_VERY_VERBOSE("[USB] IN transfer: no server response\n");
        }

        return CELL_OK;
    }

    if (toypad_type == 2) {
        /* Toy Pad OUT endpoint (0x01): Forward data to server. */
        uint32_t data_len;
        uint8_t zone = 1;  /* Default zone: CENTER */
        uint8_t seq;

        if (buf == NULL || len == NULL) {
            DEBUG_ERROR("[USB] OUT transfer with NULL buffer/len\n");
            return CELL_USBD_ERROR_FAILED;
        }

        data_len = *len;
        seq = (uint8_t)(g_usb_hooks.next_pipe_id++);

        DEBUG_PACKET("[USB] OUT transfer: pipe=0x%08X, len=%u\n",
                     (unsigned)pipe_handle, (unsigned)data_len);
        DEBUG_HEX_DUMP("[USB] OUT data", (const uint8_t*)buf, (int)data_len);

        /* Forward to PC server via UDP. */
        network_send_data(zone, seq, (const uint8_t*)buf, (int)data_len);

        return CELL_OK;
    }

    /* Should never reach here. */
    DEBUG_ERROR("[USB] Unhandled transfer: pipe=0x%08X, type=%d\n",
                (unsigned)pipe_handle, toypad_type);
    return CELL_USBD_ERROR_FAILED;
}

/* ---------------------------------------------------------------
 * Hook: my_cellUsbdClosePipe
 *
 * The game calls this to close a USB pipe.
 * We free our virtual pipe slot. For non-Toy-Pad pipes, we pass through.
 *
 * Original signature:
 *   int cellUsbdClosePipe(uint32_t pipe_handle);
 * --------------------------------------------------------------- */
int my_cellUsbdClosePipe(uint32_t pipe_handle)
{
    int toypad_type;

    toypad_type = usb_hook_is_toypad_pipe(pipe_handle);

    if (toypad_type == 0) {
        /* Non-Toy-Pad pipe: pass through to real LV2. */
        typedef int (*tramp_fn_t)(uint32_t);
        tramp_fn_t real_close = (tramp_fn_t)(void*)&g_usb_hooks.tramp_close_pipe;
        return real_close(pipe_handle);
    }

    /* Toy Pad pipe: free our virtual slot. */
    DEBUG_PRINT("[USB] cellUsbdClosePipe: Toy Pad handle=0x%08X\n",
                (unsigned)pipe_handle);
    free_pipe(pipe_handle);
    return CELL_OK;
}

/* ---------------------------------------------------------------
 * Installation
 * --------------------------------------------------------------- */

/*
 * Locate the game's cellUsbd function pointers.
 *
 * After PS3MAPI injection, the SPRX is loaded into the game's process.
 * The game's imports for cellUsbd are resolved through the game's PRX
 * import table. We need to find the actual function addresses.
 *
 * STRATEGY: We search the game's memory for the NID patterns of the
 * cellUsbd functions. Each PRX import stub looks like:
 *
 *   lis r11, <hishigh>
 *   lwz r11, <hislow>(r11)   ; load function pointer from PRX table
 *   mtctr r11
 *   bctr                      ; branch to actual function
 *
 * OR the function pointer is directly at a known offset from the
 * PRX's .got2 section.
 *
 * SIMPLIFIED APPROACH: Since this is a development/demonstration build,
 * we use a known workaround: the LEGO Dimensions game's cellUsbd
 * imports are at fixed offsets relative to the game's base address.
 * These offsets would need to be determined experimentally for the
 * specific game version (BLUS31548 or BLES02206).
 *
 * For now, we set up the hooks on self-referencing trampolines
 * and log that the game integration needs actual address discovery.
 *
 * TODO: Implement proper NID-based function location using the game's
 * PRX import table parsing.
 */
static int find_game_cellusbd_functions(void **out_init,
                                         void **out_open_pipe,
                                         void **out_transfer,
                                         void **out_close_pipe)
{
    /*
     * NOTE: Proper function location requires parsing the game's PRX
     * export/import tables. For the initial integration, we use a
     * placeholder that logs the need for real address discovery.
     *
     * The actual addresses would be determined by:
     * 1. Running the game, attaching a debugger, and reading the
     *    OPD entries for cellUsbdInit, cellUsbdOpenPipe, etc.
     * 2. OR: Scanning the game's .got2 section for NID 0xXXXXXX
     * 3. OR: Using PS3MAPI's process_get_mmap() to find the game's
     *    PRX modules and parsing their import stubs.
     *
     * Until then, return error to prevent undefined behavior.
     */
    (void)out_init;
    (void)out_open_pipe;
    (void)out_transfer;
    (void)out_close_pipe;

    DEBUG_ERROR("[USB] cellUsbd function discovery not implemented\n");
    DEBUG_ERROR("[USB] Game integration requires address scanning\n");
    DEBUG_ERROR("[USB] See usb_hooks.c:find_game_cellusbd_functions()\n");

    return -1;
}

int usb_hook_init(void *prx_toc)
{
    void *target_init;
    void *target_open_pipe;
    void *target_transfer;
    void *target_close_pipe;
    hook_ctx_t ctx;
    int ret;

    if (g_usb_hooks.initialized) {
        DEBUG_PRINT("[USB] Hooks already initialized\n");
        return 0;
    }

    memset(&g_usb_hooks, 0, sizeof(g_usb_hooks));
    g_usb_hooks.prx_toc = prx_toc;
    g_usb_hooks.next_pipe_id = 0x1000; /* Start handles above typical values */

    DEBUG_PRINT("[USB] Initializing USB hooks (PRX TOC=0x%08X)\n",
                (unsigned)(uintptr_t)prx_toc);

    /* ---------------------------------------------------------------
     * Step 1: Locate the game's cellUsbd function addresses.
     *
     * IMPORTANT: This requires the game to be running and the SPRX to
     * be loaded into its process space. The addresses vary by game
     * version and patch level.
     *
     * For now, this returns -1 and logs the requirement.
     * In production, this would scan the game's import table.
     * --------------------------------------------------------------- */
    ret = find_game_cellusbd_functions(&target_init,
                                        &target_open_pipe,
                                        &target_transfer,
                                        &target_close_pipe);
    if (ret != 0) {
        DEBUG_ERROR("[USB] Cannot install hooks without game function addresses\n");
        DEBUG_ERROR("[USB] Set g_usb_hooks.initialized=0 and retry after\n");
        DEBUG_ERROR("[USB] implementing NID-based function location\n");
        return -1;
    }

    /* ---------------------------------------------------------------
     * Step 2: Install detour hooks on each function.
     * --------------------------------------------------------------- */

    /* Hook cellUsbdInit */
    memset(&ctx, 0, sizeof(ctx));
    ctx.target_addr = target_init;
    ctx.hook_fn = (void*)my_cellUsbdInit;
    ctx.prx_toc = prx_toc;
    ctx.tramp = &g_usb_hooks.tramp_init_ptr;
    /* NOTE: ctx.tramp should point to &g_usb_hooks.tramp_init,
     * but tramp_init_ptr is incorrectly named. Fix in production. */

    if (hook_install(&ctx) != 0) {
        DEBUG_ERROR("[USB] Failed to hook cellUsbdInit\n");
        return -1;
    }
    DEBUG_PRINT("[USB] cellUsbdInit hooked\n");

    memset(&ctx, 0, sizeof(ctx));
    ctx.target_addr = target_open_pipe;
    ctx.hook_fn = (void*)my_cellUsbdOpenPipe;
    ctx.prx_toc = prx_toc;
    ctx.tramp = (hook_trampoline_t*)&g_usb_hooks.tramp_open_pipe;
    if (hook_install(&ctx) != 0) {
        DEBUG_ERROR("[USB] Failed to hook cellUsbdOpenPipe\n");
        return -1;
    }
    DEBUG_PRINT("[USB] cellUsbdOpenPipe hooked\n");

    memset(&ctx, 0, sizeof(ctx));
    ctx.target_addr = target_transfer;
    ctx.hook_fn = (void*)my_cellUsbdTransfer;
    ctx.prx_toc = prx_toc;
    ctx.tramp = (hook_trampoline_t*)&g_usb_hooks.tramp_transfer;
    if (hook_install(&ctx) != 0) {
        DEBUG_ERROR("[USB] Failed to hook cellUsbdTransfer\n");
        return -1;
    }
    DEBUG_PRINT("[USB] cellUsbdTransfer hooked\n");

    memset(&ctx, 0, sizeof(ctx));
    ctx.target_addr = target_close_pipe;
    ctx.hook_fn = (void*)my_cellUsbdClosePipe;
    ctx.prx_toc = prx_toc;
    ctx.tramp = (hook_trampoline_t*)&g_usb_hooks.tramp_close_pipe;
    if (hook_install(&ctx) != 0) {
        DEBUG_ERROR("[USB] Failed to hook cellUsbdClosePipe\n");
        return -1;
    }
    DEBUG_PRINT("[USB] cellUsbdClosePipe hooked\n");

    g_usb_hooks.initialized = 1;

    DEBUG_PRINT("[USB] All 4 USB hooks installed successfully\n");
    DEBUG_PRINT("[USB] Toy Pad emulation active (VID=0x%04X, PID=0x%04X)\n",
                TOYPAD_VID, TOYPAD_PID);

    return 0;
}

void usb_hook_shutdown(void)
{
    hook_ctx_t ctx;
    void *target_init;
    void *target_open_pipe;
    void *target_transfer;
    void *target_close_pipe;

    if (!g_usb_hooks.initialized) {
        return;
    }

    DEBUG_PRINT("[USB] Shutting down USB hooks\n");

    /* Restore original functions (requires addresses again). */
    if (find_game_cellusbd_functions(&target_init,
                                      &target_open_pipe,
                                      &target_transfer,
                                      &target_close_pipe) == 0) {
        /* Restore cellUsbdInit */
        memset(&ctx, 0, sizeof(ctx));
        ctx.target_addr = target_init;
        ctx.tramp = &g_usb_hooks.tramp_init;
        hook_remove(&ctx);

        /* Restore cellUsbdOpenPipe */
        memset(&ctx, 0, sizeof(ctx));
        ctx.target_addr = target_open_pipe;
        ctx.tramp = &g_usb_hooks.tramp_open_pipe;
        hook_remove(&ctx);

        /* Restore cellUsbdTransfer */
        memset(&ctx, 0, sizeof(ctx));
        ctx.target_addr = target_transfer;
        ctx.tramp = &g_usb_hooks.tramp_transfer;
        hook_remove(&ctx);

        /* Restore cellUsbdClosePipe */
        memset(&ctx, 0, sizeof(ctx));
        ctx.target_addr = target_close_pipe;
        ctx.tramp = &g_usb_hooks.tramp_close_pipe;
        hook_remove(&ctx);

        DEBUG_PRINT("[USB] All hooks removed\n");
    }

    /* Clear pipe pool. */
    memset(g_usb_hooks.pipes, 0, sizeof(g_usb_hooks.pipes));
    g_usb_hooks.toypad_claimed = 0;
    g_usb_hooks.initialized = 0;
}
